"""empty message

Revision ID: 11a1081fb08a
Revises: 
Create Date: 2020-01-28 15:01:37.517542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a1081fb08a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('create_on', sa.DateTime(), nullable=True),
    sa.Column('update_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('solicitation', sa.Boolean(), nullable=True),
    sa.Column('confirmation', sa.Boolean(), nullable=True),
    sa.Column('chat', sa.Boolean(), nullable=True),
    sa.Column('create_on', sa.DateTime(), nullable=True),
    sa.Column('update_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friendship_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('create_on', sa.DateTime(), nullable=True),
    sa.Column('update_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['friendship_id'], ['friendship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('friendship')
    op.drop_table('user')
    # ### end Alembic commands ###
