"""empty message

Revision ID: 4fc2fc28b404
Revises: 11a1081fb08a
Create Date: 2020-01-28 15:59:40.297531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc2fc28b404'
down_revision = '11a1081fb08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendship')
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('friendship_id', sa.INTEGER(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('create_on', sa.DATETIME(), nullable=True),
    sa.Column('update_on', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['friendship_id'], ['friendship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendship',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('friend_id', sa.INTEGER(), nullable=True),
    sa.Column('solicitation', sa.BOOLEAN(), nullable=True),
    sa.Column('confirmation', sa.BOOLEAN(), nullable=True),
    sa.Column('chat', sa.BOOLEAN(), nullable=True),
    sa.Column('create_on', sa.DATETIME(), nullable=True),
    sa.Column('update_on', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('chat IN (0, 1)'),
    sa.CheckConstraint('confirmation IN (0, 1)'),
    sa.CheckConstraint('solicitation IN (0, 1)'),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
